### ISSUE TITLE
'uno status' shows shell as "secret(pid)" instead of "shell(pid)"

### ISSUE THREAD

**Issue by ctubbsii** [apache/fluo-uno#262]
When we run `uno ashell`, the shell is listed in `uno status` as `secret(pid)` because the shell is launched with `-u root -p secret`. This is clearly not correct. There's nothing sensitive about the default root password for uno, but it's very confusing when the correct process name is not listed.

**Comment by DomGarguilo** [comment]
The issue comes from gathering the process name. In the `commands.sh` script, the last column in the process info is usually the name of the process so the script grabs that and prints it as the name. In the case of the shell process, for some reason `-u root -p secret` is included at the end after the name "shell", so `secret` is printed as the name. I think a more consistent approach would be to retrieve the name by gathering the entry after `org.apache.accumulo.start.Main` since it comes before the name in every case. I am now working to update the script accordingly. Just wanted to leave my thoughts here in case anyone had suggestions.
